### ISSUE TITLE
Suggest to support retry strategy on verification step

### ISSUE THREAD

**Issue by JohnNiang** [LinuxSuRen/api-testing#507]
*Description*:

See https://www.rfc-editor.org/rfc/rfc9110#status.409 for more.

Below is an example of test case with retry strategy:

```yaml
- name: recover
  request:
    api: /content.halo.run/v1alpha1/posts/{{(index .listPosts.items 0).post.metadata.name}}
    method: DELETE
  expect:
    statusCode: 200
  retry:
    on:
      statusCode: 409
    count: 10
    interval: 10s
```

[optional *Relevant Links*:]

- https://www.rfc-editor.org/rfc/rfc9110#status.409
- https://skywalking.apache.org/docs/skywalking-infra-e2e/latest/en/setup/configuration-file/#verify

**Comment by LinuxSuRen** [comment]
In a microservices architecture, users might need to wait until all the related services are ready. The following usage could achieve the desired outcome:

```yaml
name: aiums
api: |
  {{default "http://localhost:18080" (env "SERVER")}}
items:
  - name: login
    before:
      items:
        - httpReady("http://gateway:17001/actuator/health", 2400, 'components.discoveryComposite.components.eureka.details.applications["AUTH"] == 1')
    request:
      api: /auth/login
      method: POST
      header:
        Content-Type: application/json
      body: |
        {
          "userName": "admin",
          "password": "admin"
        }
```

cc @JohnNiang
