### ISSUE TITLE
Support before/after at the test suite level

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#72]
It could be similar with https://github.com/LinuxSuRen/api-testing/pull/69. See the following example:

```yaml
name: Gitlab
before:
  items:
    - "waitPod('default-ns', 'app=gitlab', '2m')"
items:
- name: projects
  request:
    api: https://gitlab.com/api/v4/projects
  before:
    items:
      - "sleep(1)"
```

There are some desired functions needed:

* waitPod: wait until the pod is ready
* createK3d
* delK3d: delete a k3d cluster

## References
* https://github.com/k3d-io/k3d
